version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: xsolla_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: xsolla
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-init.sql
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  xsolla_api:
    build: .
    environment:
      DEV: "true"
      CONN_DB: "postgres://xsolla_user:qwerty@db:5432/xsolla"
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
