version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: xsolla_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: xsolla
    volumes:
       - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"